Traceback (most recent call last):
  File "main.py", line 413, in <module>
  File "main.py", line 391, in run
  File "main.py", line 166, in main
  File "main.py", line 19, in __init__
pygame.error: Couldn't open resources/protag.png
Traceback (most recent call last):
  File "main.py", line 413, in <module>
  File "main.py", line 391, in run
  File "main.py", line 288, in main
pygame.error: display Surface quit
